import pymongo
import dns
from bson.objectid import ObjectId
from mongotriggers import MongoTrigger

client = pymongo.MongoClient("mongodb+srv://SRDewan:abcd1234@database.vvxaz.mongodb.net/Data?retryWrites=true&w=majority")
triggers = MongoTrigger(client)
db = client["Data"]
tags = db["Tags"]

pretags = [
                    'Computer Programming',
                    'Discrete Structures',
                    'Real Analysis',
                    'Intro to Computing Technology',
                    'Digital Systems and Microcontrollers',
                    'Data Structures and Algorithms',
                    'Introduction to Software Systems',
                    'Network Signals and Systems',
                    'Electronic Workshop-1',
                    'Computing in Sciences-1',
                    'Introduction to Linguistics-1',
                    'Making of Contemporary World',
                    'Human Sciences Lab-1',
                    'Introduction to IoT',
                    'Linear Algebra',
                    'Analog Electronic Circuits',
                    'Information and Communication',
                    'Computing in Sciences II',
                    'Classical Mechanics',
                    'General and Structural Chemistry',
                    'Computational Linguistics 1',
                    'Making of the Contemporary India',
                    'Thinking and Knowing in the Human Sciences-I',

                    'Probability and Statistics',
                    'Computational Linguistics',
                    'Algorithm Analysis and Design',

                    'Internship',
                    'Resume',
                    'BTP',
                    'Honours',
                    'CASE Project',
                    'Arts',
                    'Sports',
                    'Value Education',
                    'CASE Project',
                    'Seminar',
                    'Assignment',
                    'Wiki',
                    'Community',
                    'Freshers',
                    'Felicity',
                    'Others',

                    'Design and Analysis of Software Systems',
                    'Machine, Data and Learning',
                    'Introduction to Human Sciences',
                    'Science II',
                    'Automata Theory',
                    'Introduction to Quantum Information and Computation',
                    'Introduction to Coding Theory',
                    'Software Programming for Performance',
                    'Digital Signal Analysis',
                    'Introduction to Brain and Cognition',
                    'Computer Graphics',
                    'Communication Theory',
                    'Introduction to Processor Architecture',
                    'Introduction to Human Sciences',
                    'VLSI Design',
                    'Introduction to Bio Electronics',
                    'Computer System Organization',
                    'Thermodynamics',
                    'Statistical Mechanics',
                    'Biomolecular structures',
                    'Organic Chemistry',
                    'Language Typology and Universals',
                    'Introduction to NLP',
                    'Research Methods in Human Sciences',
                    'Science, Technology and Society',
                    'System and Network Security',
                    'Principles of Information Security',
                    'Information Security Audit and Assurance',
                    'Computing Tools',
                    'Advanced Bioinformatics',
                    'Topics in Nanosciences',
                    'Nonlinear Dynamics',
                    'Linguistic Data 2: Collection & Modeling',
                    'Social Computing',
                    'Time Frequency Analysis',
                    'Signal Detection and Estimation Theory',
                    'Medical Image Analysis',
                    'Computer Vision',
                    'Statistical Methods in AI (SMAI)',
                    'Applied Electromagnetics',
                    'Topics in Coding Theory',
                    'Design Verification and System Verilog',
                    'Digital VLSI Design',
                    'Flexible Electronics',
                    'Robotics: Planning and Navigation',
                    'Introduction to UAV Design',
                    'Advances in Robotics and Control',
                    'Disaster Management',
                    'Advanced Structural Analysis',
                    'Design of Hydraulic Structures',
                    'Stability of Structures',
                    'Earthquake Engineering',
                    'Remote Sensing',
                    'Green Buildings',
                    'Nonlinear Dynamics',
                    'Topics in Nanosciences',
                    'Optimization Methods',
                    'Advanced Algorithms',
                    'Database Systems',
                    'Software Engineering',
                    'Distributed Systems',
                    'ICTs for Development',
                    'Information Security Audit and Assurance',
                    'Introduction to Game Theory',
                    'Internals of Application Servers',
                    'Cognitive Neuroscience',
                    'Music, Mind, and Technology',
                    'Usability Engineering',
                    'Deep Learning: Theory and Practices',
                    'Distributed Data Systems',
                    'Advanced Optimization: Theory and Applications',
                    'Behavioral Research: Statistical Methods',
                    'Hydro Informatics',
                    'Differential Equations',
                    'Multivariate Analysis',
                    'Linear partial differential equations and variational calculus',
                    'Molecular Modeling and Simulations',
                    'Introduction to Particle Physics',
                    'Machine Learning for Natural Sciences',
                    'Physics of Soft Condensed Matter',
                    'Digital Humanities Project',
                    'Ethics',
                    'Readings in Indian Literatures',
                    'Comprehension of Indian Music',
                    'Alternate Religious Traditions in Indian History',
                    'Introduction to Philosophy of Technology',
                    'Literature, History and Belonging in Hyderabad',
                    'Literature - American Classics'
                ]

def notify():
    print("Added")
    
triggers.register_insert_trigger(notify, 'Data', 'tags')

triggers.tail_oplog()
for i in pretags:
    tags.insert_one({"name": i, "weekly": 0, "lifetime": 0})
triggers.stop_tail()

# try:
#     for insert_change in db.posts.watch([{'$match': {'operationType': 'update']):
#         print(insert_change)

# except pymongo.errors.PyMongoError:
#     # We know it's unrecoverable:
#     print("Error occured")

pretags2 = [
                    {'name' : 'Computer Programming', 'value' : 0},
                    {'name' : 'Discrete Structures', 'value' : 0},
                    {'name' : 'Real Analysis', 'value' : 0},
                    {'name' : 'Intro to Computing Technology', 'value' : 0},
                    {'name' : 'Digital Systems and Microcontrollers', 'value' : 0},
                    {'name' : 'Data Structures and Algorithms', 'value' : 0},
                    {'name' : 'Introduction to Software Systems', 'value' : 0},
                    {'name' : 'Network Signals and Systems', 'value' : 0},
                    {'name' : 'Electronic Workshop-1', 'value' : 0},
                    {'name' : 'Computing in Sciences-1', 'value' : 0},
                    {'name' : 'Introduction to Linguistics-1', 'value' : 0},
                    {'name' : 'Making of Contemporary World', 'value' : 0},
                    {'name' : 'Human Sciences Lab-1', 'value' : 0},
                    {'name' : 'Introduction to IoT', 'value' : 0},
                    {'name' : 'Linear Algebra', 'value' : 0},
                    {'name' : 'Analog Electronic Circuits', 'value' : 0},
                    {'name' : 'Information and Communication', 'value' : 0},
                    {'name' : 'Computing in Sciences II', 'value' : 0},
                    {'name' : 'Classical Mechanics', 'value' : 0},
                    {'name' : 'General and Structural Chemistry', 'value' : 0},
                    {'name' : 'Computational Linguistics 1', 'value' : 0},
                    {'name' : 'Making of the Contemporary India', 'value' : 0},
                    {'name' : 'Thinking and Knowing in the Human Sciences-I', 'value' : 0},

                    {'name' : 'Probability and Statistics', 'value' : 0},
                    {'name' : 'Computational Linguistics', 'value' : 0},
                    {'name' : 'Algorithm Analysis and Design', 'value': 0},

                    {'name' : 'Internship', 'value' : 0},
                    {'name' : 'Resume', 'value' : 0},
                    {'name' : 'BTP', 'value' : 0},
                    {'name' : 'Honours', 'value' : 0},
                    {'name' : 'CASE Project', 'value' : 0},
                    {'name' : 'Arts', 'value' : 0},
                    {'name' : 'Sports', 'value' : 0},
                    {'name' : 'Value Education', 'value' : 0},
                    {'name' : 'CASE Project', 'value' : 0},
                    {'name' : 'Seminar', 'value' : 0},
                    {'name' : 'Assignment', 'value' : 0},
                    {'name' : 'Wiki', 'value' : 0},
                    {'name' : 'Community', 'value' : 0},
                    {'name' : 'Freshers', 'value' : 0},
                    {'name' : 'Felicity', 'value' : 0},
                    {'name' : 'Others', 'value' : 0},

                    {'name' : 'Design and Analysis of Software Systems', 'value' : 0},
                    {'name' : 'Machine, Data and Learning', 'value' : 0},
                    {'name' : 'Introduction to Human Sciences', 'value' : 0},
                    {'name' : 'Science II', 'value' : 0},
                    {'name' : 'Automata Theory', 'value' : 0},
                    {'name' : 'Introduction to Quantum Information and Computation', 'value' : 0},
                    {'name' : 'Introduction to Coding Theory', 'value' : 0},
                    {'name' : 'Software Programming for Performance', 'value' : 0},
                    {'name' : 'Digital Signal Analysis', 'value' : 0},
                    {'name' : 'Introduction to Brain and Cognition', 'value' : 0},
                    {'name' : 'Computer Graphics', 'value' : 0},
                    {'name' : 'Communication Theory', 'value' : 0},
                    {'name' : 'Introduction to Processor Architecture', 'value' : 0},
                    {'name' : 'Introduction to Human Sciences', 'value' : 0},
                    {'name' : 'VLSI Design', 'value' : 0},
                    {'name' : 'Introduction to Bio Electronics', 'value' : 0},
                    {'name' : 'Computer System Organization', 'value' : 0},
                    {'name' : 'Thermodynamics', 'value' : 0},
                    {'name' : 'Statistical Mechanics', 'value' : 0},
                    {'name' : 'Biomolecular structures', 'value' : 0},
                    {'name' : 'Organic Chemistry', 'value' : 0},
                    {'name' : 'Language Typology and Universals', 'value' : 0},
                    {'name' : 'Introduction to NLP', 'value' : 0},
                    {'name' : 'Research Methods in Human Sciences', 'value' : 0},
                    {'name' : 'Science, Technology and Society', 'value' : 0},
                    {'name' : 'System and Network Security', 'value' : 0},
                    {'name' : 'Principles of Information Security', 'value' : 0},
                    {'name' : 'Information Security Audit and Assurance', 'value' : 0},
                    {'name' : 'Computing Tools', 'value' : 0},
                    {'name' : 'Advanced Bioinformatics', 'value' : 0},
                    {'name' : 'Topics in Nanosciences', 'value' : 0},
                    {'name' : 'Nonlinear Dynamics', 'value' : 0},
                    {'name' : 'Linguistic Data 2: Collection & Modeling', 'value' : 0},
                    {'name' : 'Social Computing', 'value' : 0},
                    {'name' : 'Time Frequency Analysis', 'value' : 0},
                    {'name' : 'Signal Detection and Estimation Theory', 'value' : 0},
                    {'name' : 'Medical Image Analysis', 'value' : 0},
                    {'name' : 'Computer Vision', 'value' : 0},
                    {'name' : 'Statistical Methods in AI (SMAI)', 'value' : 0},
                    {'name' : 'Applied Electromagnetics', 'value' : 0},
                    {'name' : 'Topics in Coding Theory', 'value' : 0},
                    {'name' : 'Design Verification and System Verilog', 'value' : 0},
                    {'name' : 'Digital VLSI Design', 'value' : 0},
                    {'name' : 'Flexible Electronics', 'value' : 0},
                    {'name' : 'Robotics: Planning and Navigation', 'value' : 0},
                    {'name' : 'Introduction to UAV Design', 'value' : 0},
                    {'name' : 'Advances in Robotics and Control', 'value' : 0},
                    {'name' : 'Disaster Management', 'value' : 0},
                    {'name' : 'Advanced Structural Analysis', 'value' : 0},
                    {'name' : 'Design of Hydraulic Structures', 'value' : 0},
                    {'name' : 'Stability of Structures', 'value' : 0},
                    {'name' : 'Earthquake Engineering', 'value' : 0},
                    {'name' : 'Remote Sensing', 'value' : 0},
                    {'name' : 'Green Buildings', 'value' : 0},
                    {'name' : 'Nonlinear Dynamics', 'value' : 0},
                    {'name' : 'Topics in Nanosciences', 'value' : 0},
                    {'name' : 'Optimization Methods', 'value' : 0},
                    {'name' : 'Advanced Algorithms', 'value' : 0},
                    {'name' : 'Database Systems', 'value' : 0},
                    {'name' : 'Software Engineering', 'value' : 0},
                    {'name' : 'Distributed Systems', 'value' : 0},
                    {'name' : 'ICTs for Development', 'value' : 0},
                    {'name' : 'Information Security Audit and Assurance', 'value' : 0},
                    {'name' : 'Introduction to Game Theory', 'value' : 0},
                    {'name' : 'Internals of Application Servers', 'value' : 0},
                    {'name' : 'Cognitive Neuroscience', 'value' : 0},
                    {'name' : 'Music, Mind, and Technology', 'value' : 0},
                    {'name' : 'Usability Engineering', 'value' : 0},
                    {'name' : 'Deep Learning: Theory and Practices', 'value' : 0},
                    {'name' : 'Distributed Data Systems', 'value' : 0},
                    {'name' : 'Advanced Optimization: Theory and Applications', 'value' : 0},
                    {'name' : 'Behavioral Research: Statistical Methods', 'value' : 0},
                    {'name' : 'Hydro Informatics', 'value' : 0},
                    {'name' : 'Differential Equations', 'value' : 0},
                    {'name' : 'Multivariate Analysis', 'value' : 0},
                    {'name' : 'Linear partial differential equations and variational calculus', 'value' : 0},
                    {'name' : 'Molecular Modeling and Simulations', 'value' : 0},
                    {'name' : 'Introduction to Particle Physics', 'value' : 0},
                    {'name' : 'Machine Learning for Natural Sciences', 'value' : 0},
                    {'name' : 'Physics of Soft Condensed Matter', 'value' : 0},
                    {'name' : 'Digital Humanities Project', 'value' : 0},
                    {'name' : 'Ethics', 'value' : 0},
                    {'name' : 'Readings in Indian Literatures', 'value' : 0},
                    {'name' : 'Comprehension of Indian Music', 'value' : 0},
                    {'name' : 'Alternate Religious Traditions in Indian History', 'value' : 0},
                    {'name' : 'Introduction to Philosophy of Technology', 'value' : 0},
                    {'name' : 'Literature, History and Belonging in Hyderabad', 'value' : 0},
                    {'name' : 'Literature - American Classics', 'value' : 0}
                ]